import datetime

#lista para almacenar los experimentos
listaDeExperimentos = [
    ["Experimento 1", "26/11/2024", "fisica", [5, 6, 2, 7, 8, 9]],
]

#crear todas las funciones que se necesitan
#funcion para agregar experimentos
def agregar_experimento(lista):
    pass

#funcion para eliminar un experimento
def eliminar_experimento(lista):
    pass

#funcion para visualizar los experimentos
def visualizar_experimentos(lista):
    pass

#Funcion para calcular estadisticas
def calcular_estadisticas(lista):
    pass

#funcion de comparar experimentos
def comparar_experimentos(lista):
    pass

#funcion para generar un informe
def generar_informe(lista):
    pass

#funcion para mostrar el menu
def mostrar_menu():
    pass

#funcion principal
def main():
    pass

main()
